services:
  # -------------- Observability back‑end stack --------------
  prometheus:
    image: prom/prometheus:v3.3.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert-rules.yaml:/etc/prometheus/alert_rules.yaml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

  alertmanager:
    image: prom/alertmanager:v0.28.1
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/log/containers:ro
    command: -config.file=/etc/promtail/config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.68.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP HTTP

  grafana:
    image: grafana/grafana:11.6.1
    depends_on: [prometheus, loki, jaeger]
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana-data:/var/lib/grafana

  # -------------- Tiny application --------------
  tiny-app:
    image: tiny-app:latest
    build:
      context: ./tiny-app
    depends_on: [jaeger]
    ports:
      - "8080:8080"
    labels:
      logging: "promtail"

  # -------------- Alert sink for Tiny stack --------------
  alert-logger:
    image: mendhak/http-https-echo:36
    environment:
      HTTP_PORT: 5678
    ports:
      - "5678:5678"

volumes:
  grafana-data: {}
