global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tiny-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['tiny-app:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert_rules.yaml
